/**
 * Realtime Event Simulator
 * 
 * Generates mock real-time events for testing the WebSocket layer.
 * Can be started/stopped via API.
 */

import {
  publishCandleUpdate,
  publishPatternDetected,
  publishSignalCreated,
  publishScenarioUpdate,
  publishRegimeUpdate,
  publishMetaBrainUpdate,
  publishMemoryMatch,
  publishTreeUpdate
} from './realtime.publishers.js';

let simulatorInterval: ReturnType<typeof setInterval> | null = null;
let tickCount = 0;

const SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT'];
const PATTERNS = ['ascending_triangle', 'descending_triangle', 'double_bottom', 'head_and_shoulders', 'bull_flag', 'wedge', 'channel_breakout'];
const REGIMES = ['TREND', 'COMPRESSION', 'RANGE', 'BREAKOUT', 'ACCUMULATION', 'DISTRIBUTION', 'EXHAUSTION'];

function randomFrom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Generate a mock candle update
 */
function emitCandleUpdate(): void {
  const symbol = randomFrom(SYMBOLS);
  const basePrices: Record<string, number> = { BTCUSDT: 87000, ETHUSDT: 3200, SOLUSDT: 145 };
  const base = basePrices[symbol] || 100;
  const vol = base * 0.005;

  const o = base + (Math.random() - 0.5) * vol * 2;
  const c = o + (Math.random() - 0.48) * vol;
  const h = Math.max(o, c) + Math.random() * vol * 0.5;
  const l = Math.min(o, c) - Math.random() * vol * 0.5;

  publishCandleUpdate(symbol, '1m', {
    t: Date.now(),
    o: Math.round(o * 100) / 100,
    h: Math.round(h * 100) / 100,
    l: Math.round(l * 100) / 100,
    c: Math.round(c * 100) / 100,
    v: Math.round(500 + Math.random() * 2000),
  });
}

/**
 * Generate occasional pattern detection events
 */
function maybeEmitPattern(): void {
  if (Math.random() > 0.15) return; // ~15% chance per tick

  const symbol = randomFrom(SYMBOLS);
  const basePrices: Record<string, number> = { BTCUSDT: 87000, ETHUSDT: 3200, SOLUSDT: 145 };
  const base = basePrices[symbol] || 100;

  publishPatternDetected(
    symbol,
    '1h',
    randomFrom(PATTERNS),
    randomFrom(['BULLISH', 'BEARISH', 'NEUTRAL']),
    0.55 + Math.random() * 0.35,
    Math.round(base * (0.98 + Math.random() * 0.04) * 100) / 100,
    'Auto-detected by TA engine'
  );
}

/**
 * Generate occasional signal creation
 */
function maybeEmitSignal(): void {
  if (Math.random() > 0.08) return; // ~8% chance per tick

  const symbol = randomFrom(SYMBOLS);
  const basePrices: Record<string, number> = { BTCUSDT: 87000, ETHUSDT: 3200, SOLUSDT: 145 };
  const base = basePrices[symbol] || 100;
  const dir = Math.random() > 0.5 ? 'LONG' as const : 'SHORT' as const;

  const entry = base;
  const stop = dir === 'LONG' ? base * 0.97 : base * 1.03;
  const target = dir === 'LONG' ? base * 1.08 : base * 0.92;

  publishSignalCreated(
    symbol, '1d', dir,
    Math.round(entry),
    Math.round(stop),
    Math.round(target),
    0.6 + Math.random() * 0.3,
    randomFrom(['TREND_FOLLOW', 'BREAKOUT', 'MEAN_REVERSION']),
    'Generated by decision engine'
  );
}

/**
 * Generate occasional scenario updates
 */
function maybeEmitScenario(): void {
  if (Math.random() > 0.1) return; // ~10% chance per tick

  const symbol = randomFrom(SYMBOLS);
  publishScenarioUpdate(
    symbol, '1d',
    randomFrom(['bullish_breakout', 'range_consolidation', 'bearish_rejection']),
    0.4 + Math.random() * 0.4,
    [
      { scenario: 'range_consolidation', probability: 0.25 + Math.random() * 0.2 },
      { scenario: 'bearish_pullback', probability: 0.1 + Math.random() * 0.15 },
    ],
    Math.random() * 0.4
  );
}

/**
 * Generate occasional regime changes
 */
function maybeEmitRegime(): void {
  if (Math.random() > 0.05) return; // ~5% chance per tick

  const symbol = randomFrom(SYMBOLS);
  const prev = randomFrom(REGIMES) as any;
  let next = randomFrom(REGIMES) as any;
  while (next === prev) next = randomFrom(REGIMES) as any;

  publishRegimeUpdate(
    symbol, '1d',
    prev, next,
    0.6 + Math.random() * 0.3,
    `Transition detected: ${prev} → ${next}`
  );
}

/**
 * Generate occasional metabrain updates
 */
function maybeEmitMetaBrain(): void {
  if (Math.random() > 0.06) return;

  publishMetaBrainUpdate(
    'BTCUSDT', '1d',
    randomFrom(['CLASSIC_TA', 'DEEP_MARKET']) as any,
    randomFrom(['SAFE', 'CONSERVATIVE', 'NORMAL', 'AGGRESSIVE']) as any,
    Math.random() < 0.1,
    0.5 + Math.random() * 1.0,
    ['TREND_FOLLOW', 'BREAKOUT'],
    Math.random() < 0.3 ? ['MEAN_REVERSION'] : [],
    ['Auto-rebalance cycle']
  );
}

/**
 * Single simulation tick
 */
function simulationTick(): void {
  tickCount++;

  // Always emit candle
  emitCandleUpdate();

  // Probabilistic events
  maybeEmitPattern();
  maybeEmitSignal();
  maybeEmitScenario();
  maybeEmitRegime();
  maybeEmitMetaBrain();
}

/**
 * Start the simulator
 */
export function startSimulator(intervalMs: number = 2000): void {
  if (simulatorInterval) return;

  tickCount = 0;
  simulatorInterval = setInterval(simulationTick, intervalMs);
  console.log(`[Realtime Simulator] Started with ${intervalMs}ms interval`);
}

/**
 * Stop the simulator
 */
export function stopSimulator(): void {
  if (simulatorInterval) {
    clearInterval(simulatorInterval);
    simulatorInterval = null;
    console.log(`[Realtime Simulator] Stopped after ${tickCount} ticks`);
  }
}

/**
 * Get simulator status
 */
export function getSimulatorStatus(): { running: boolean; tickCount: number } {
  return {
    running: simulatorInterval !== null,
    tickCount,
  };
}
